services:
  database:
    image: postgres:18
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: .env # set POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    volumes:
      - database-data:/var/lib/postgresql
      - ./backup:/backup
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  database-data:
